name = "ninja-recipe-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "ninja-recipe-api"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

[vars]
ENVIRONMENT = "production" 