name = "ninja-recipe-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "264f5e50d1b547f593b4f4d40d2dbb77"
preview_id = "264f5e50d1b547f593b4f4d40d2dbb77"

[vars]
ENVIRONMENT = "production" 